package main

import (
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

type SwaggerSpec struct {
	BasePath string                           `json:"basePath"`
	Tags     []Tag                            `json:"tags"`
	Paths    map[string]map[string]*Operation `json:"paths"`
}

type Tag struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Operation struct {
	Tags        []string     `json:"tags"`
	OperationID string       `json:"operationId"`
	Summary     string       `json:"summary"`
	Description string       `json:"description"`
	Parameters  []*Parameter `json:"parameters"`
	Deprecated  bool         `json:"deprecated"`
}

type Parameter struct {
	Name        string   `json:"name"`
	In          string   `json:"in"` // "path", "query", "body", "header"
	Description string   `json:"description"`
	Required    bool     `json:"required"`
	Type        string   `json:"type"` // "string", "integer", "boolean", "array"
	Format      string   `json:"format"`
	Schema      *Schema  `json:"schema"`
}

type Schema struct {
	Ref string `json:"$ref"`
}

func main() {
	if len(os.Args) < 2 {
		fmt.Println("Usage: go run scratch/generate_api.go <looker_host> [port]")
		fmt.Println("Example: go run scratch/generate_api.go sandbox.looker-devrel.com")
		os.Exit(1)
	}

	host := os.Args[1]
	port := "443"
	if len(os.Args) > 2 {
		port = os.Args[2]
	}

	targetURL := host
	if !strings.HasPrefix(targetURL, "http://") && !strings.HasPrefix(targetURL, "https://") {
		targetURL = "https://" + host
		if !strings.Contains(host, ":") {
			targetURL = fmt.Sprintf("https://%s:%s", host, port)
		}
	}
	if !strings.HasSuffix(targetURL, "/api/4.0/swagger.json") {
		targetURL = strings.TrimSuffix(targetURL, "/")
		targetURL = targetURL + "/api/4.0/swagger.json"
	}

	fmt.Printf("Fetching swagger.json from %s ...\n", targetURL)

	tr := &http.Transport{
		TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
	}
	client := &http.Client{Transport: tr}
	resp, err := client.Get(targetURL)
	if err != nil {
		fmt.Printf("Failed to fetch swagger.json: %v\n", err)
		os.Exit(1)
	}
	defer func() { _ = resp.Body.Close() }()

	if resp.StatusCode != http.StatusOK {
		fmt.Printf("Server returned status %s\n", resp.Status)
		os.Exit(1)
	}

	b, err := io.ReadAll(resp.Body)
	if err != nil {
		fmt.Printf("Failed to read response body: %v\n", err)
		os.Exit(1)
	}

	outputFile := "internal/cmd/api_generated.go"

	var spec SwaggerSpec
	if err := json.Unmarshal(b, &spec); err != nil {
		fmt.Printf("Failed to parse swagger JSON: %v\n", err)
		os.Exit(1)
	}

	// Group operations by tag
	tagOperations := make(map[string][]*OpMetadata)
	tagInfo := make(map[string]string)

	for _, t := range spec.Tags {
		tagInfo[t.Name] = t.Description
	}

	for path, pathItem := range spec.Paths {
		for method, op := range pathItem {
			if op.OperationID == "" {
				continue
			}
			tag := "Default"
			if len(op.Tags) > 0 {
				tag = op.Tags[0]
			}

			// Parse parameters
			var pathParams []string
			var requiredQueryParams []string
			var bodyParam string
			queryFlags := make(map[string]*Parameter)

			// Find path params in order of path appearance
			re := regexp.MustCompile(`\{([^}]+)\}`)
			matches := re.FindAllStringSubmatch(path, -1)
			for _, m := range matches {
				pathParams = append(pathParams, m[1])
			}

			for _, p := range op.Parameters {
				if p.In == "path" {
					// Already captured in order by regex, but verify it exists
					continue
				} else if p.In == "body" {
					bodyParam = p.Name
				} else if p.In == "query" {
					if p.Required {
						requiredQueryParams = append(requiredQueryParams, p.Name)
					} else {
						queryFlags[p.Name] = p
					}
				}
			}

			metadata := &OpMetadata{
				Path:                path,
				Method:              strings.ToUpper(method),
				OperationID:         op.OperationID,
				Summary:             op.Summary,
				Description:         op.Description,
				PathParams:          pathParams,
				RequiredQueryParams: requiredQueryParams,
				BodyParam:           bodyParam,
				QueryFlags:          queryFlags,
				Deprecated:          op.Deprecated,
			}

			tagOperations[tag] = append(tagOperations[tag], metadata)
		}
	}

	// Generate Code
	var out strings.Builder
	out.WriteString(`// Code generated by generate_api.go. DO NOT EDIT.
package cmd

import (
	"bytes"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"

	"github.com/spf13/cobra"
)

var ApiCmd = &cobra.Command{
	Use:   "api",
	Short: "Make raw Looker API calls based on Swagger spec",
	Long:  "Make raw Looker API calls based on Swagger spec. Use 'gzr api help' to list categories.",
}

func init() {
	RootCmd.AddCommand(ApiCmd)
}
`)

	// Sort tags for deterministic code generation
	var tags []string
	for t := range tagOperations {
		tags = append(tags, t)
	}
	sort.Strings(tags)

	for _, tag := range tags {
		ops := tagOperations[tag]
		sort.Slice(ops, func(i, j int) bool {
			return ops[i].OperationID < ops[j].OperationID
		})

		tagCmdName := fmt.Sprintf("api%sCmd", cleanTagName(tag))
		tagUse := strings.ToLower(strings.ReplaceAll(tag, " ", "_"))
		tagDesc := tagInfo[tag]
		if tagDesc == "" {
			tagDesc = tag + " commands"
		}

		out.WriteString(fmt.Sprintf("\n// %s category\n", tag))
		out.WriteString(fmt.Sprintf("var %s = &cobra.Command{\n", tagCmdName))
		out.WriteString(fmt.Sprintf("\tUse:   %s,\n", strconv.Quote(tagUse)))
		out.WriteString(fmt.Sprintf("\tShort: %s,\n", strconv.Quote(tagDesc)))
		out.WriteString("}\n\n")

		out.WriteString(fmt.Sprintf("func init() {\n\tApiCmd.AddCommand(%s)\n}\n", tagCmdName))

		for _, op := range ops {
			opCmdName := fmt.Sprintf("api%s%sCmd", cleanTagName(tag), cleanOpName(op.OperationID))
			
			// Construct Use string
			var useParts []string
			useParts = append(useParts, op.OperationID)
			for _, p := range op.PathParams {
				useParts = append(useParts, fmt.Sprintf("[%s]", strings.ToUpper(p)))
			}
			for _, p := range op.RequiredQueryParams {
				useParts = append(useParts, fmt.Sprintf("[%s]", strings.ToUpper(p)))
			}
			if op.BodyParam != "" {
				useParts = append(useParts, fmt.Sprintf("[%s_JSON_FILE_OR_-]", strings.ToUpper(op.BodyParam)))
			}
			useStr := strings.Join(useParts, " ")

			numArgs := len(op.PathParams) + len(op.RequiredQueryParams)
			if op.BodyParam != "" {
				numArgs++
			}

			out.WriteString(fmt.Sprintf("\nvar %s = &cobra.Command{\n", opCmdName))
			out.WriteString(fmt.Sprintf("\tUse:   %s,\n", strconv.Quote(useStr)))
			out.WriteString(fmt.Sprintf("\tShort: %s,\n", strconv.Quote(op.Summary)))
			out.WriteString(fmt.Sprintf("\tLong:  %s,\n", strconv.Quote(op.Description)))
			out.WriteString(fmt.Sprintf("\tArgs:  cobra.ExactArgs(%d),\n", numArgs))
			out.WriteString("\tRunE: func(cmd *cobra.Command, args []string) error {\n")

			// queryParams map definition
			out.WriteString("\t\tqueryParams := make(map[string]string)\n")
			
			// Sort query flags for deterministic generation
			var qFlags []string
			for f := range op.QueryFlags {
				qFlags = append(qFlags, f)
			}
			sort.Strings(qFlags)

			for _, fName := range qFlags {
				p := op.QueryFlags[fName]
				if p.Type == "boolean" {
					out.WriteString(fmt.Sprintf("\t\tif cmd.Flags().Changed(\"%s\") {\n", fName))
					out.WriteString(fmt.Sprintf("\t\t\tval, _ := cmd.Flags().GetBool(\"%s\")\n", fName))
					out.WriteString(fmt.Sprintf("\t\t\tqueryParams[\"%s\"] = strconv.FormatBool(val)\n", fName))
					out.WriteString("\t\t}\n")
				} else {
					out.WriteString(fmt.Sprintf("\t\tif cmd.Flags().Changed(\"%s\") {\n", fName))
					out.WriteString(fmt.Sprintf("\t\t\tval, _ := cmd.Flags().GetString(\"%s\")\n", fName))
					out.WriteString(fmt.Sprintf("\t\t\tqueryParams[\"%s\"] = val\n", fName))
					out.WriteString("\t\t}\n")
				}
			}

			// Call executeApiCallGeneric
			pathParamsList := "[]string{"
			for i, p := range op.PathParams {
				if i > 0 {
					pathParamsList += ", "
				}
				pathParamsList += fmt.Sprintf("\"%s\"", p)
			}
			pathParamsList += "}"

			reqQueryParamsList := "[]string{"
			for i, p := range op.RequiredQueryParams {
				if i > 0 {
					reqQueryParamsList += ", "
				}
				reqQueryParamsList += fmt.Sprintf("\"%s\"", p)
			}
			reqQueryParamsList += "}"

			bodyParamStr := ""
			if op.BodyParam != "" {
				bodyParamStr = op.BodyParam
			}

			out.WriteString(fmt.Sprintf("\t\treturn executeApiCallGeneric(cmd, \"%s\", \"%s\", %s, %s, \"%s\", queryParams, args)\n",
				op.Method, op.Path, pathParamsList, reqQueryParamsList, bodyParamStr))
			out.WriteString("\t},\n")
			out.WriteString("}\n\n")

			// init registration and flags
			out.WriteString(fmt.Sprintf("func init() {\n\t%s.AddCommand(%s)\n", tagCmdName, opCmdName))
			for _, fName := range qFlags {
				p := op.QueryFlags[fName]
				desc := strconv.Quote(p.Description)
				if p.Type == "boolean" {
					out.WriteString(fmt.Sprintf("\t%s.Flags().Bool(\"%s\", false, %s)\n", opCmdName, fName, desc))
				} else {
					out.WriteString(fmt.Sprintf("\t%s.Flags().String(\"%s\", \"\", %s)\n", opCmdName, fName, desc))
				}
			}
			out.WriteString("}\n")
		}
	}

	// Append executeApiCallGeneric helper
	out.WriteString(`
func executeApiCallGeneric(cmd *cobra.Command, method, pathTemplate string, pathParams, requiredQueryParams []string, bodyParam string, queryParams map[string]string, args []string) error {
	ctx := cmd.Context()
	c, err := initClient(ctx, false)
	if err != nil {
		return err
	}

	actualPath := pathTemplate
	argIdx := 0

	// 1. Replace path parameters
	for _, paramName := range pathParams {
		if argIdx >= len(args) {
			return fmt.Errorf("missing required path parameter: %s", paramName)
		}
		val := args[argIdx]
		argIdx++
		actualPath = strings.ReplaceAll(actualPath, "{"+paramName+"}", url.PathEscape(val))
	}

	// 2. Parse required query parameters
	qParams := make(map[string]string)
	for _, paramName := range requiredQueryParams {
		if argIdx >= len(args) {
			return fmt.Errorf("missing required query parameter: %s", paramName)
		}
		val := args[argIdx]
		argIdx++
		qParams[paramName] = val
	}

	// 3. Parse body parameter
	var bodyReader io.Reader
	if bodyParam != "" {
		if argIdx >= len(args) {
			return fmt.Errorf("missing required body parameter (JSON file path or '-' for stdin)")
		}
		bodyFile := args[argIdx]
		argIdx++

		var bodyBytes []byte
		if bodyFile == "-" {
			bodyBytes, err = io.ReadAll(os.Stdin)
		} else {
			bodyBytes, err = os.ReadFile(bodyFile)
		}
		if err != nil {
			return fmt.Errorf("failed to read body from %s: %w", bodyFile, err)
		}
		bodyReader = bytes.NewReader(bodyBytes)
	}

	// 4. Construct URL
	u, err := url.Parse(c.Session.Config.BaseUrl)
	if err != nil {
		return fmt.Errorf("invalid base URL: %w", err)
	}
	u.Path = "/api/4.0" + actualPath

	q := u.Query()
	// Set required query params
	for k, v := range qParams {
		q.Set(k, v)
	}
	// Set optional query params from flags
	for k, v := range queryParams {
		q.Set(k, v)
	}
	u.RawQuery = q.Encode()

	// 5. Create HTTP request
	req, err := http.NewRequestWithContext(ctx, method, u.String(), bodyReader)
	if err != nil {
		return fmt.Errorf("failed to create request: %w", err)
	}
	if bodyReader != nil {
		req.Header.Set("Content-Type", "application/json")
	}

	// 6. Execute request
	resp, err := c.Session.Client.Do(req)
	if err != nil {
		return fmt.Errorf("API request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	// 7. Read response
	outBytes, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("failed to read response body: %w", err)
	}

	if resp.StatusCode >= 400 {
		return fmt.Errorf("API returned error %s: %s", resp.Status, string(outBytes))
	}

	fmt.Println(string(outBytes))
	return nil
}
`)

	// Write output
	dir := filepath.Dir(outputFile)
	_ = os.MkdirAll(dir, 0755)
	err = os.WriteFile(outputFile, []byte(out.String()), 0644)
	if err != nil {
		fmt.Printf("Failed to write output file %s: %v\n", outputFile, err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated %s\n", outputFile)
}

type OpMetadata struct {
	Path                string
	Method              string
	OperationID         string
	Summary             string
	Description         string
	PathParams          []string
	RequiredQueryParams []string
	BodyParam           string
	QueryFlags          map[string]*Parameter
	Deprecated          bool
}

func cleanTagName(tag string) string {
	// Convert "UserAttribute" to "UserAttribute", "ApiAuth" to "ApiAuth"
	// Remove spaces and non-alphanumeric
	reg := regexp.MustCompile(`[^a-zA-Z0-9]`)
	return reg.ReplaceAllString(tag, "")
}

func cleanOpName(op string) string {
	// Convert "create_query_task" to "CreateQueryTask" (CamelCase)
	parts := strings.Split(op, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}
